server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2432757689


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

pagehelper:
  propertyName: propertyValue
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  defaultCount: true